In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('ds_salaries.csv')

In [2]:
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [3]:
df.tail()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [4]:
df.sample(5)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
58,58,2020,SE,FT,Data Scientist,120000,USD,120000,US,50,US,L
366,366,2022,SE,FT,Data Engineer,136000,USD,136000,US,0,US,M
482,482,2022,EX,FT,Data Engineer,324000,USD,324000,US,100,US,M
423,423,2022,SE,FT,Data Scientist,180000,USD,180000,US,0,US,M
301,301,2022,SE,FT,Data Scientist,80000,GBP,104702,GB,0,GB,M

In [15]:
df.shape

(607, 12)

In [16]:
df.columns

Index(['Unnamed: 0', 'work_year', 'experience_level', 'employment_type',
       'job_title', 'salary', 'salary_currency', 'salary_in_usd',
       'employee_residence', 'remote_ratio', 'company_location',
       'company_size'],
      dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    object
 3   employment_type     607 non-null    object
 4   job_title           607 non-null    object
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    object
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    object
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    object
 11  company_size        607 non-null    object
dtypes: int64(5), object(7)
memory usage: 57.0+ KB

In [18]:
df.dtypes

Unnamed: 0             int64
work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [19]:
df.describe()

       Unnamed: 0    work_year        salary  salary_in_usd  remote_ratio
count  607.000000   607.000000  6.070000e+02     607.000000     607.00000
mean   303.000000  2021.405272  3.240001e+05  112297.869852      70.92257
std    175.370085     0.692133  1.544357e+06   70957.259411      40.70913
min      0.000000  2020.000000  4.000000e+03    2859.000000       0.00000
25%    151.500000  2021.000000  7.000000e+04   62726.000000      50.00000
50%    303.000000  2022.000000  1.150000e+05  101570.000000     100.00000
75%    454.500000  2022.000000  1.650000e+05  150000.000000     100.00000
max    606.000000  2022.000000  3.040000e+07  600000.000000     100.00000

In [20]:
df.isnull().sum()

Unnamed: 0            0
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df['experience_level'].value_counts()

experience_level
SE    280
MI    213
EN     88
EX     26
Name: count, dtype: int64

In [23]:
df['employment_type'].value_counts()

employment_type
FT    588
PT     10
CT      5
FL      4
Name: count, dtype: int64

In [25]:
df['company_size'].value_counts()

company_size
M    326
L    198
S     83
Name: count, dtype: int64

In [26]:
df['remote_ratio'].value_counts()

remote_ratio
100    381
0      127
50      99
Name: count, dtype: int64

In [28]:
df['employee_residence'].value_counts()

employee_residence
US    332
GB     44
IN     30
CA     29
DE     25
FR     18
ES     15
GR     13
JP      7
PT      6
PK      6
BR      6
NL      5
IT      4
RU      4
PL      4
AE      3
TR      3
AU      3
VN      3
AT      3
DK      2
NG      2
HU      2
MX      2
SI      2
RO      2
BE      2
SG      2
PH      1
CN      1
HN      1
NZ      1
UA      1
IQ      1
CL      1
MT      1
IR      1
CO      1
HR      1
BG      1
KE      1
MD      1
RS      1
HK      1
LU      1
JE      1
CZ      1
PR      1
AR      1
DZ      1
MY      1
TN      1
EE      1
BO      1
IE      1
CH      1
Name: count, dtype: int64

In [29]:
df['salary_currency'].value_counts()

salary_currency
USD    398
EUR     95
GBP     44
INR     27
CAD     18
JPY      3
PLN      3
TRY      3
HUF      2
MXN      2
CNY      2
SGD      2
DKK      2
AUD      2
BRL      2
CLP      1
CHF      1
Name: count, dtype: int64

In [30]:
df['work_year'].value_counts()

work_year
2022    318
2021    217
2020     72
Name: count, dtype: int64

In [48]:
df['job_title'].value_counts()

job_title
Data Scientist                              143
Data Engineer                               132
Data Analyst                                 97
Machine Learning Engineer                    41
Research Scientist                           16
Data Science Manager                         12
Data Architect                               11
Machine Learning Scientist                    8
Big Data Engineer                             8
Director of Data Science                      7
AI Scientist                                  7
Principal Data Scientist                      7
Data Science Consultant                       7
Data Analytics Manager                        7
BI Data Analyst                               6
Computer Vision Engineer                      6
ML Engineer                                   6
Lead Data Engineer                            6
Applied Data Scientist                        5
Business Data Analyst                         5
Data Engineering Manager                      5
Head of Data                                  5
Data Analytics Engineer                       4
Head of Data Science                          4
Applied Machine Learning Scientist            4
Analytics Engineer                            4
Machine Learning Developer                    3
Data Science Engineer                         3
Lead Data Analyst                             3
Machine Learning Infrastructure Engineer      3
Lead Data Scientist                           3
Principal Data Engineer                       3
Computer Vision Software Engineer             3
Product Data Analyst                          2
ETL Developer                                 2
Cloud Data Engineer                           2
Financial Data Analyst                        2
Director of Data Engineering                  2
Principal Data Analyst                        2
Machine Learning Manager                      1
Marketing Data Analyst                        1
3D Computer Vision Researcher                 1
Finance Data Analyst                          1
Data Specialist                               1
Staff Data Scientist                          1
Big Data Architect                            1
Head of Machine Learning                      1
NLP Engineer                                  1
Lead Machine Learning Engineer                1
Data Analytics Lead                           1
Name: count, dtype: int64

In [37]:
# Salary Analysis 
# Overall Salary Stats

df['salary_in_usd'].describe()

count       607.000000
mean     112297.869852
std       70957.259411
min        2859.000000
25%       62726.000000
50%      101570.000000
75%      150000.000000
max      600000.000000
Name: salary_in_usd, dtype: float64

In [39]:
# Salary by Experience Level
# How does salary grow with experience?

df.groupby('experience_level')['salary_in_usd'].mean().sort_values()

experience_level
EN     61643.318182
MI     87996.056338
SE    138617.292857
EX    199392.038462
Name: salary_in_usd, dtype: float64

In [34]:
df.groupby('experience_level')['salary_in_usd'].mean().sort_values(ascending=False)

experience_level
EX    199392.038462
SE    138617.292857
MI     87996.056338
EN     61643.318182
Name: salary_in_usd, dtype: float64

In [49]:
# Salary by Job Title (Top Paying Roles)
# What are the top-paying data science jobs? 

df.groupby('job_title')['salary_in_usd'].mean().sort_values(ascending=False)

job_title
Data Analytics Lead                         405000.000000
Principal Data Engineer                     328333.333333
Financial Data Analyst                      275000.000000
Principal Data Scientist                    215242.428571
Director of Data Science                    195074.000000
Data Architect                              177873.909091
Applied Data Scientist                      175655.000000
Analytics Engineer                          175000.000000
Data Specialist                             165000.000000
Head of Data                                160162.600000
Machine Learning Scientist                  158412.500000
Data Science Manager                        158328.500000
Director of Data Engineering                156738.000000
Head of Data Science                        146718.750000
Applied Machine Learning Scientist          142068.750000
Lead Data Engineer                          139724.500000
Data Analytics Manager                      127134.285714
Cloud Data Engineer                         124647.000000
Data Engineering Manager                    123227.200000
Principal Data Analyst                      122500.000000
ML Engineer                                 117504.000000
Machine Learning Manager                    117104.000000
Lead Data Scientist                         115190.000000
Data Engineer                               112725.000000
Research Scientist                          109019.500000
Data Scientist                              108187.832168
Computer Vision Software Engineer           105248.666667
Staff Data Scientist                        105000.000000
Machine Learning Engineer                   104880.146341
Machine Learning Infrastructure Engineer    101145.000000
Big Data Architect                           99703.000000
Data Analyst                                 92893.061856
Lead Data Analyst                            92203.000000
Marketing Data Analyst                       88654.000000
Lead Machine Learning Engineer               87932.000000
Machine Learning Developer                   85860.666667
Head of Machine Learning                     79039.000000
Business Data Analyst                        76691.200000
Data Science Engineer                        75803.333333
BI Data Analyst                              74755.166667
Data Science Consultant                      69420.714286
AI Scientist                                 66135.571429
Data Analytics Engineer                      64799.250000
Finance Data Analyst                         61896.000000
ETL Developer                                54957.000000
Big Data Engineer                            51974.000000
Computer Vision Engineer                     44419.333333
NLP Engineer                                 37236.000000
Product Data Analyst                         13036.000000
3D Computer Vision Researcher                 5409.000000
Name: salary_in_usd, dtype: float64

In [41]:
# Remote Work Analysis
# Average Salary by Remote Ratio
# Does Remote work affect salary? 
# Remote ratio meanings: 
''' 
0 -> Onsite
50 -> Hybrid
100 -> Fully remote
'''

df.groupby('remote_ratio')['salary_in_usd'].mean()

remote_ratio
0      106354.622047
50      80823.030303
100    122457.454068
Name: salary_in_usd, dtype: float64

In [42]:
# Location-Based Analysis
# Salary by Company Location
# Which countries pay best? 

df.groupby('employee_residence')['salary_in_usd'].mean().sort_values(ascending=False)

employee_residence
MY    200000.000000
PR    160000.000000
US    149194.117470
NZ    125000.000000
CH    122346.000000
AU    108042.666667
RU    105750.000000
SG    104176.500000
JP    103537.714286
JE    100000.000000
AE    100000.000000
DZ    100000.000000
IQ    100000.000000
CA     97085.310345
BE     85699.000000
DE     85552.560000
GB     81403.159091
BG     80000.000000
AT     76738.666667
BO     75000.000000
IE     71444.000000
CZ     69999.000000
HK     66022.000000
SI     63831.000000
IT     61600.000000
NL     60956.600000
AR     60000.000000
FR     59886.611111
LU     59102.000000
ES     57593.400000
GR     56331.230769
PL     56177.500000
BR     54634.666667
RO     51419.000000
PH     45760.000000
HR     45618.000000
CN     43331.000000
PT     42862.500000
CL     40038.000000
IN     37322.333333
DK     37252.500000
HU     35997.000000
EE     32974.000000
TN     31875.000000
VN     30800.000000
NG     30000.000000
MT     28369.000000
PK     27462.833333
RS     25532.000000
CO     21844.000000
TR     20096.666667
HN     20000.000000
MX     18185.000000
MD     18000.000000
UA     13400.000000
KE      9272.000000
IR      4000.000000
Name: salary_in_usd, dtype: float64

In [43]:
# Company Size Impact
# Do big companies pay more?
# Typical sizes:
'''
S - Small
M - Medium
L - Large
'''

df.groupby('company_size')['salary_in_usd'].mean()

company_size
L    119242.994949
M    116905.466258
S     77632.674699
Name: salary_in_usd, dtype: float64

In [67]:
# Creating useful columns
# Salary banding 

df['salary_band'] = pd.cut(
    df['salary_in_usd'],
    bins=[0, 50000, 100000, 150000, 300000],
    labels=['Low', 'Medium', 'High', 'Very High']
)

In [68]:
df['salary_band'].value_counts()

salary_band
Medium       195
High         158
Very High    137
Low          107
Name: count, dtype: int64

In [47]:
# Filtration
# Senior Remote Roles Only

df[
    (df['experience_level'] == 'SE') & (df['remote_ratio'] == 100)
]

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,salary_band
6,6,2020,SE,FT,Lead Data Scientist,190000,USD,190000,US,100,US,S,Very High
17,17,2020,SE,FT,Big Data Engineer,100000,EUR,114047,PL,100,GB,S,High
32,32,2020,SE,FT,Data Scientist,60000,EUR,68428,GR,100,US,L,Medium
47,47,2020,SE,FT,Data Engineer,188000,USD,188000,US,100,US,L,Very High
54,54,2020,SE,FL,Computer Vision Engineer,60000,USD,60000,RU,100,US,S,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,596,2022,SE,FT,Data Scientist,210000,USD,210000,US,100,US,M,Very High
597,597,2022,SE,FT,Data Analyst,170000,USD,170000,US,100,US,M,Very High
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M,Very High
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M,High
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M,High

In [51]:
# Sorting and Presenting Data

df.sort_values(by='salary_in_usd', ascending=False).head(20)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,salary_band
252,252,2021,EX,FT,Principal Data Engineer,600000,USD,600000,US,100,US,L,NaN
97,97,2021,MI,FT,Financial Data Analyst,450000,USD,450000,US,100,US,L,NaN
33,33,2020,MI,FT,Research Scientist,450000,USD,450000,US,0,US,M,NaN
157,157,2021,MI,FT,Applied Machine Learning Scientist,423000,USD,423000,US,50,US,L,NaN
225,225,2021,EX,CT,Principal Data Scientist,416000,USD,416000,US,100,US,S,NaN
63,63,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L,NaN
523,523,2022,SE,FT,Data Analytics Lead,405000,USD,405000,US,100,US,L,NaN
519,519,2022,SE,FT,Applied Data Scientist,380000,USD,380000,US,100,US,L,NaN
25,25,2020,EX,FT,Director of Data Science,325000,USD,325000,US,100,US,L,NaN
482,482,2022,EX,FT,Data Engineer,324000,USD,324000,US,100,US,M,NaN
93,93,2021,SE,FT,Lead Data Engineer,276000,USD,276000,US,0,US,L,Very High
78,78,2021,MI,CT,ML Engineer,270000,USD,270000,US,100,US,L,Very High
534,534,2022,SE,FT,Data Architect,266400,USD,266400,US,100,US,M,Very High
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,Very High
416,416,2022,SE,FT,Data Scientist,260000,USD,260000,US,100,US,M,Very High
231,231,2021,SE,FT,ML Engineer,256000,USD,256000,US,100,US,S,Very High
37,37,2020,EN,FT,Machine Learning Engineer,250000,USD,250000,US,50,US,L,Very High
167,167,2021,EX,FT,Director of Data Science,250000,USD,250000,US,0,US,L,Very High
337,337,2022,SE,FT,Data Engineer,243900,USD,243900,US,100,US,M,Very High
309,309,2022,EX,FT,Data Engineer,242000,USD,242000,US,100,US,M,Very High

In [59]:
# Exporting Cleaned and Analyzed Dataset

df.to_csv('cleaned_ds_salaries.csv', index=False)

In [54]:
df[df['job_title']=='OR']

Empty DataFrame
Columns: [Unnamed: 0, work_year, experience_level, employment_type, job_title, salary, salary_currency, salary_in_usd, employee_residence, remote_ratio, company_location, company_size, salary_band]
Index: []

In [56]:
df.groupby('company_location')['salary_in_usd'].mean()

company_location
AE    100000.000000
AS     18053.000000
AT     72920.750000
AU    108042.666667
BE     85699.000000
BR     18602.666667
CA     99823.733333
CH     64114.000000
CL     40038.000000
CN     71665.500000
CO     21844.000000
CZ     50937.000000
DE     81887.214286
DK     54386.333333
DZ    100000.000000
EE     32974.000000
ES     53060.142857
FR     63970.666667
GB     81583.042553
GR     52293.090909
HN     20000.000000
HR     45618.000000
HU     35735.000000
IE     71444.000000
IL    119059.000000
IN     28581.750000
IQ    100000.000000
IR      4000.000000
IT     36366.500000
JP    114127.333333
KE      9272.000000
LU     43942.666667
MD     18000.000000
MT     28369.000000
MX     32123.333333
MY     40000.000000
NG     30000.000000
NL     54945.750000
NZ    125000.000000
PK     13333.333333
PL     66082.500000
PT     47793.750000
RO     60000.000000
RU    157500.000000
SG     89294.000000
SI     63831.000000
TR     20096.666667
UA     13400.000000
US    144055.261972
VN      4000.000000
Name: salary_in_usd, dtype: float64

In [70]:
df=pd.read_csv('cleaned_ds_salaries.csv')

In [71]:
df.sample(20)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,salary_band
227,227,2021,MI,FT,Data Scientist,75000,EUR,88654,DE,50,DE,L,Medium
484,484,2022,SE,FT,Data Engineer,210000,USD,210000,US,100,US,M,Very High
345,345,2022,SE,FT,Data Engineer,156600,USD,156600,US,100,US,M,Very High
460,460,2022,MI,FT,Machine Learning Infrastructure Engineer,53000,EUR,58255,PT,50,PT,L,Medium
504,504,2022,SE,FT,Data Engineer,115000,USD,115000,US,100,US,M,High
293,293,2022,MI,FT,Data Scientist,90000,USD,90000,US,0,US,M,Medium
508,508,2022,EN,FT,Research Scientist,120000,USD,120000,US,100,US,L,High
62,62,2020,EN,PT,Data Scientist,19000,EUR,21669,IT,50,IT,S,Low
486,486,2022,SE,FT,Data Scientist,230000,USD,230000,US,100,US,M,Very High
209,209,2021,SE,FT,Data Analytics Manager,120000,USD,120000,US,0,US,L,High
174,174,2021,SE,FT,Research Scientist,51400,EUR,60757,PT,50,PT,L,Medium
159,159,2021,EN,FT,Machine Learning Engineer,125000,USD,125000,US,100,US,S,High
516,516,2022,SE,FT,Data Science Manager,152500,USD,152500,US,100,US,M,Very High
428,428,2022,SE,FT,Data Scientist,140400,USD,140400,US,0,US,L,High
268,268,2021,MI,FT,Data Engineer,250000,TRY,28016,TR,100,TR,M,Low
59,59,2020,MI,FT,Data Scientist,138350,USD,138350,US,100,US,M,High
295,295,2022,MI,FT,Data Engineer,150000,USD,150000,US,100,US,M,High
456,456,2022,SE,FT,Data Engineer,105000,USD,105000,US,100,US,M,High
597,597,2022,SE,FT,Data Analyst,170000,USD,170000,US,100,US,M,Very High
423,423,2022,SE,FT,Data Scientist,180000,USD,180000,US,0,US,M,Very High

In [72]:
df.isnull().sum()

Unnamed: 0            0
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
salary_band           7
dtype: int64

In [75]:
df.fillna('Very High').inplace=True
df

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,salary_band
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,Medium
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,Very High
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,High
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,Low
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M,Very High
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M,High
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M,High
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M,High
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L,Very High

In [76]:
df.isnull().sum()

Unnamed: 0            0
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
salary_band           7
dtype: int64

In [77]:
df=pd.read_csv('ds_salaries.csv')
df

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [103]:
# Creating useful columns
# Salary banding 

df['salary_band'] = pd.cut(
    df['salary_in_usd'],
    bins=[0, 50000, 100000, 200000, 600000],
    labels=['Low', 'Medium', 'High', 'Very High']
)

In [104]:
df

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,salary_band
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,Medium
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,Very High
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,High
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,Low
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M,High
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M,High
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M,High
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M,High
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L,High

In [105]:
df.isnull().sum()

Unnamed: 0            0
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
salary_band           0
dtype: int64

In [106]:
df.head(60)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,salary_band
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,Medium
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,Very High
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,High
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,Low
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,High
5,5,2020,EN,FT,Data Analyst,72000,USD,72000,US,100,US,L,Medium
6,6,2020,SE,FT,Lead Data Scientist,190000,USD,190000,US,100,US,S,High
7,7,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,Low
8,8,2020,MI,FT,Business Data Analyst,135000,USD,135000,US,100,US,L,High
9,9,2020,SE,FT,Lead Data Engineer,125000,USD,125000,NZ,50,NZ,S,High
10,10,2020,EN,FT,Data Scientist,45000,EUR,51321,FR,0,FR,S,Medium
11,11,2020,MI,FT,Data Scientist,3000000,INR,40481,IN,0,IN,L,Low
12,12,2020,EN,FT,Data Scientist,35000,EUR,39916,FR,0,FR,M,Low
13,13,2020,MI,FT,Lead Data Analyst,87000,USD,87000,US,100,US,L,Medium
14,14,2020,MI,FT,Data Analyst,85000,USD,85000,US,100,US,L,Medium
15,15,2020,MI,FT,Data Analyst,8000,USD,8000,PK,50,PK,L,Low
16,16,2020,EN,FT,Data Engineer,4450000,JPY,41689,JP,100,JP,S,Low
17,17,2020,SE,FT,Big Data Engineer,100000,EUR,114047,PL,100,GB,S,High
18,18,2020,EN,FT,Data Science Consultant,423000,INR,5707,IN,50,IN,M,Low
19,19,2020,MI,FT,Lead Data Engineer,56000,USD,56000,PT,100,US,M,Medium
20,20,2020,MI,FT,Machine Learning Engineer,299000,CNY,43331,CN,0,CN,M,Low
21,21,2020,MI,FT,Product Data Analyst,450000,INR,6072,IN,100,IN,L,Low
22,22,2020,SE,FT,Data Engineer,42000,EUR,47899,GR,50,GR,L,Low
23,23,2020,MI,FT,BI Data Analyst,98000,USD,98000,US,0,US,M,Medium
24,24,2020,MI,FT,Lead Data Scientist,115000,USD,115000,AE,0,AE,L,High
25,25,2020,EX,FT,Director of Data Science,325000,USD,325000,US,100,US,L,Very High
26,26,2020,EN,FT,Research Scientist,42000,USD,42000,NL,50,NL,L,Low
27,27,2020,SE,FT,Data Engineer,720000,MXN,33511,MX,0,MX,S,Low
28,28,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L,Medium
29,29,2020,SE,FT,Machine Learning Manager,157000,CAD,117104,CA,50,CA,L,High
30,30,2020,MI,FT,Data Engineering Manager,51999,EUR,59303,DE,100,DE,S,Medium
31,31,2020,EN,FT,Big Data Engineer,70000,USD,70000,US,100,US,L,Medium
32,32,2020,SE,FT,Data Scientist,60000,EUR,68428,GR,100,US,L,Medium
33,33,2020,MI,FT,Research Scientist,450000,USD,450000,US,0,US,M,Very High
34,34,2020,MI,FT,Data Analyst,41000,EUR,46759,FR,50,FR,L,Low
35,35,2020,MI,FT,Data Engineer,65000,EUR,74130,AT,50,AT,L,Medium
36,36,2020,MI,FT,Data Science Consultant,103000,USD,103000,US,100,US,L,High
37,37,2020,EN,FT,Machine Learning Engineer,250000,USD,250000,US,50,US,L,Very High
38,38,2020,EN,FT,Data Analyst,10000,USD,10000,NG,100,NG,S,Low
39,39,2020,EN,FT,Machine Learning Engineer,138000,USD,138000,US,100,US,S,High
40,40,2020,MI,FT,Data Scientist,45760,USD,45760,PH,100,US,S,Low
41,41,2020,EX,FT,Data Engineering Manager,70000,EUR,79833,ES,50,ES,L,Medium
42,42,2020,MI,FT,Machine Learning Infrastructure Engineer,44000,EUR,50180,PT,0,PT,M,Medium
43,43,2020,MI,FT,Data Engineer,106000,USD,106000,US,100,US,L,High
44,44,2020,MI,FT,Data Engineer,88000,GBP,112872,GB,50,GB,L,High
45,45,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S,Low
46,46,2020,MI,FT,Data Scientist,60000,GBP,76958,GB,100,GB,S,Medium
47,47,2020,SE,FT,Data Engineer,188000,USD,188000,US,100,US,L,High
48,48,2020,MI,FT,Data Scientist,105000,USD,105000,US,100,US,L,High
49,49,2020,MI,FT,Data Engineer,61500,EUR,70139,FR,50,FR,L,Medium
50,50,2020,EN,FT,Data Analyst,450000,INR,6072,IN,0,IN,S,Low
51,51,2020,EN,FT,Data Analyst,91000,USD,91000,US,100,US,L,Medium
52,52,2020,EN,FT,AI Scientist,300000,DKK,45896,DK,50,DK,S,Low
53,53,2020,EN,FT,Data Engineer,48000,EUR,54742,PK,100,DE,L,Medium
54,54,2020,SE,FL,Computer Vision Engineer,60000,USD,60000,RU,100,US,S,Medium
55,55,2020,SE,FT,Principal Data Scientist,130000,EUR,148261,DE,100,DE,M,High
56,56,2020,MI,FT,Data Scientist,34000,EUR,38776,ES,100,ES,M,Low
57,57,2020,MI,FT,Data Scientist,118000,USD,118000,US,100,US,M,High
58,58,2020,SE,FT,Data Scientist,120000,USD,120000,US,50,US,L,High
59,59,2020,MI,FT,Data Scientist,138350,USD,138350,US,100,US,M,High

In [107]:
# Exporting Cleaned and Analyzed Dataset

df.to_csv('cleaned_ds_salaries.csv', index=False)